"""Initial migration: create role_messages and reaction_roles tables.

Revision ID: cc9c35f74c61
Revises:
Create Date: 2026-01-04 23:53:51.808281

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc9c35f74c61"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reaction_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("emoji", sa.String(length=100), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "emoji", name="uq_guild_emoji"),
    )
    with op.batch_alter_table("reaction_roles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reaction_roles_guild_id"), ["guild_id"], unique=False
        )

    op.create_table(
        "role_messages",
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("message_id"),
    )
    with op.batch_alter_table("role_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_role_messages_guild_id"), ["guild_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_messages_guild_id"))

    op.drop_table("role_messages")
    with op.batch_alter_table("reaction_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reaction_roles_guild_id"))

    op.drop_table("reaction_roles")
    # ### end Alembic commands ###
